### ISSUE TITLE
[Docs]:README

### ISSUE THREAD

**Issue by abhisar-yadav** [PiyushKalyanpy/GyanaGuru#590]
### Description

 spelling errors and other grammatical errors in the README. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by deepthibalasubramanian** [comment]
Hi, I would like to update the README file by making the description about GyanaGuru more welcoming for the visitors, by drafting the description in a more inclusive yet formal way. Requesting assignment of issue to me, with GSSoC'23 label, so that I can submit the changes for updating into the project. Thanks, @PiyushKalyanpy

**Comment by abhisar-yadav** [comment]
@PiyushKalyanpy I have already raised a PR regarding this issue! Kindly review it.
